version: "3.9"

services:
  api:
    image: mohsin1920/docker-cicd-learning:latest

    container_name: docker-cicd-learning

    restart: unless-stopped

    ports:
      - "8000:8000"

    env_file:
      - .env